### ISSUE TITLE
Write test for run_analysis

### ISSUE THREAD

**Issue by joshwlambert** [Neves-P/DAISIErobustness#12]

**Comment by Neves-P** [comment]
Done in 898c71383355a93fad283f5657b88e71c55aef6a

**Comment by Neves-P** [comment]
TODO: test alternative flows, and constraint failures

**Comment by Neves-P** [comment]
> TODO: test alternative flows, and constraint failures

sim_constraint test done here: fbf75bd354231b62278072f0ef871f0e2d7c69c9
