### ISSUE TITLE
Add tests on trait after trait branch merge into develop/master in DAISIE package

### ISSUE THREAD

**Issue by xieshu95** [Neves-P/DAISIErobustness#26]

**Comment by Neves-P** [comment]
Depends on:
`rsetienne/DAISIE@trait` merging with `master`

**Comment by Neves-P** [comment]
> 
> 
> Depends on:
> `rsetienne/DAISIE@trait` merging with `master`

Done! Now on `rsetienne/DAISIE@geodynamics-traits`. In the future will go to `develop` and then `master`.

#26 will be closed on a version following v1.0.0.

**Comment by Neves-P** [comment]
Closed by @xieshu95 here: 39480a80350524d510d6636c381ed1b211380b96
